#!/usr/bin/env python3
"""Exact finite audit for the tetrahedral SIC Naimark -> 2T -> Fock -> E6 envelope.

The validator checks:
1. the 24-element binary tetrahedral spin group;
2. the 4D minimal-Naimark outcome representation R;
3. R ~= rho + rho*chi for chi=(det R)^2;
4. the complete seven-irrep character table generated by {chi,rho};
5. exterior-power/Fock decomposition of R;
6. center sign = Fock parity;
7. McKay adjacency for tensoring by rho is affine E6;
8. the current tetrahedral supercharge coefficient space has rank two and uses
   only one spinor summand, so full-E6 realization by that single Q is rejected.

This is a finite representation-theory audit, not a novelty or physical-SUSY proof.
"""
from __future__ import annotations

import cmath
import itertools
import math


TOL = 3.0e-8


def zeros(n: int, m: int):
    return [[0j for _ in range(m)] for _ in range(n)]


def eye(n: int):
    a = zeros(n, n)
    for i in range(n):
        a[i][i] = 1.0 + 0j
    return a


def madd(a, b):
    return [[a[i][j] + b[i][j] for j in range(len(a[0]))] for i in range(len(a))]


def msub(a, b):
    return [[a[i][j] - b[i][j] for j in range(len(a[0]))] for i in range(len(a))]


def mscale(c, a):
    return [[c * a[i][j] for j in range(len(a[0]))] for i in range(len(a))]


def mmul(a, b):
    n, k, m = len(a), len(b), len(b[0])
    assert len(a[0]) == k
    out = zeros(n, m)
    for i in range(n):
        for j in range(m):
            out[i][j] = sum(a[i][r] * b[r][j] for r in range(k))
    return out


def dagger(a):
    return [[a[i][j].conjugate() for i in range(len(a))] for j in range(len(a[0]))]


def trace(a):
    return sum(a[i][i] for i in range(min(len(a), len(a[0]))))


def det2(a):
    return a[0][0] * a[1][1] - a[0][1] * a[1][0]


def det4(a):
    # Leibniz is fine for 4x4.
    total = 0j
    for p in itertools.permutations(range(4)):
        inv = sum(1 for i in range(4) for j in range(i + 1, 4) if p[i] > p[j])
        sign = -1 if inv % 2 else 1
        term = 1 + 0j
        for i in range(4):
            term *= a[i][p[i]]
        total += sign * term
    return total


def maxabs(a):
    return max(abs(z) for row in a for z in row)


def assert_close(a, b, tol=TOL):
    err = maxabs(msub(a, b))
    assert err < tol, err


def vdot(u, v):
    return sum(x.conjugate() * y for x, y in zip(u, v))


def mvec(a, v):
    return [sum(a[i][j] * v[j] for j in range(len(v))) for i in range(len(a))]


def outer(u, v):
    return [[u[i] * v[j].conjugate() for j in range(len(v))] for i in range(len(u))]


def matrix_key(a):
    vals = []
    for row in a:
        for z in row:
            vals.extend((round(z.real, 10), round(z.imag, 10)))
    return tuple(vals)


def rank(a, tol=1e-9):
    # Small complex Gaussian elimination.
    m = [row[:] for row in a]
    rows, cols = len(m), len(m[0])
    r = 0
    for c in range(cols):
        pivot = max(range(r, rows), key=lambda i: abs(m[i][c]), default=r)
        if r >= rows or abs(m[pivot][c]) < tol:
            continue
        m[r], m[pivot] = m[pivot], m[r]
        piv = m[r][c]
        m[r] = [z / piv for z in m[r]]
        for i in range(rows):
            if i == r:
                continue
            f = m[i][c]
            if abs(f) >= tol:
                m[i] = [m[i][j] - f * m[r][j] for j in range(cols)]
        r += 1
        if r == rows:
            break
    return r


I2 = eye(2)
SX = [[0j, 1 + 0j], [1 + 0j, 0j]]
SY = [[0j, -1j], [1j, 0j]]
SZ = [[1 + 0j, 0j], [0j, -1 + 0j]]


def tetra_vectors():
    r = 1.0 / math.sqrt(3.0)
    return [
        (r, r, r),
        (r, -r, -r),
        (-r, r, -r),
        (-r, -r, r),
    ]


def spinor_from_bloch(n):
    nx, ny, nz = n
    a = math.sqrt((1.0 + nz) / 2.0)
    b = (nx + 1j * ny) / math.sqrt(2.0 * (1.0 + nz))
    return [a + 0j, b]


def analysis_map(lambdas):
    return [[z.conjugate() / math.sqrt(2.0) for z in lam] for lam in lambdas]


def generate_2t():
    gx = mscale(1j, SX)
    gy = mscale(1j, SY)
    gz = mscale(1j, SZ)
    u3 = madd(mscale(-0.5, I2), mscale(-0.5j, madd(madd(SX, SY), SZ)))
    gens = [gx, gy, gz, u3]
    group = {matrix_key(I2): I2}
    changed = True
    while changed:
        changed = False
        current = list(group.values())
        for a in current:
            for g in gens:
                for b in (mmul(a, g), mmul(g, a)):
                    k = matrix_key(b)
                    if k not in group:
                        group[k] = b
                        changed = True
    assert len(group) == 24
    return list(group.values()), (gx, gy, gz, u3)


def outcome_rep(g, lambdas):
    r = zeros(4, 4)
    pi = []
    phases = []
    for a, lam in enumerate(lambdas):
        y = mvec(g, lam)
        ovs = [vdot(target, y) for target in lambdas]
        b = max(range(4), key=lambda j: abs(ovs[j]))
        ov = ovs[b]
        assert abs(abs(ov) - 1.0) < 1e-8
        phase = ov / abs(ov)
        r[b][a] = phase
        pi.append(b)
        phases.append(phase)
    assert sorted(pi) == [0, 1, 2, 3]
    return r, pi, phases


def cinner(a, b):
    return sum(x.conjugate() * y for x, y in zip(a, b)) / len(a)


def elementary_sym4_from_traces(r):
    # Newton identities for eigenvalues of a 4x4 matrix.
    p1 = trace(r)
    p2 = trace(mmul(r, r))
    p3 = trace(mmul(mmul(r, r), r))
    p4 = trace(mmul(mmul(r, r), mmul(r, r)))
    e0 = 1 + 0j
    e1 = p1
    e2 = (p1 * p1 - p2) / 2.0
    e3 = (p1**3 - 3 * p1 * p2 + 2 * p3) / 6.0
    e4 = (p1**4 - 6 * p1 * p1 * p2 + 3 * p2 * p2 + 8 * p1 * p3 - 6 * p4) / 24.0
    return [e0, e1, e2, e3, e4]


def round_mult(z):
    assert abs(z.imag) < 2e-7, z
    n = round(z.real)
    assert abs(z.real - n) < 2e-7, z
    assert n >= 0
    return n


def main():
    lambdas = [spinor_from_bloch(n) for n in tetra_vectors()]
    v = analysis_map(lambdas)
    assert_close(mmul(dagger(v), v), I2)

    group, (gx, gy, gz, u3) = generate_2t()
    records = []
    for g in group:
        r, pi, phases = outcome_rep(g, lambdas)
        assert_close(mmul(v, g), mmul(r, v))
        records.append((g, r, pi, phases))

    # Outcome projector onto Im(V), and invariant two-dimensional complement.
    p_v = mmul(v, dagger(v))
    p_w = msub(eye(4), p_v)
    assert rank(p_v) == 2
    assert rank(p_w) == 2

    # Define the nontrivial C3 character chi=(det R)^2.
    delta = [det4(r) for _, r, _, _ in records]
    chi = [d * d for d in delta]
    for x in chi:
        assert abs(x**3 - 1) < 2e-7
        assert abs(abs(x) - 1) < 2e-7

    # Homomorphism check for chi.
    rec_by_key = {matrix_key(g): (r, pi, ph) for g, r, pi, ph in records}
    chi_by_key = {matrix_key(g): x for (g, _, _, _), x in zip(records, chi)}
    for g, h in itertools.product(group, repeat=2):
        gh = mmul(g, h)
        assert abs(
            chi_by_key[matrix_key(gh)]
            - chi_by_key[matrix_key(g)] * chi_by_key[matrix_key(h)]
        ) < 2e-7

    # chi is trivial on Q8 and nontrivial on the C3 quotient.
    q8 = [
        I2,
        mscale(-1, I2),
        gx, mscale(-1, gx),
        gy, mscale(-1, gy),
        gz, mscale(-1, gz),
    ]
    for q in q8:
        assert abs(chi_by_key[matrix_key(q)] - 1) < 2e-7
    assert abs(chi_by_key[matrix_key(u3)] - 1) > 0.5

    # R = rho + rho*chi: characters on the invariant summands.
    char_rho = [trace(g) for g, _, _, _ in records]
    char_im = [trace(mmul(p_v, r)) for _, r, _, _ in records]
    char_w = [trace(mmul(p_w, r)) for _, r, _, _ in records]
    for a, b in zip(char_im, char_rho):
        assert abs(a - b) < 2e-7
    for w, rr, x in zip(char_w, char_rho, chi):
        assert abs(w - x * rr) < 2e-7

    chi2 = [x * x for x in chi]
    char_3 = [abs(z) ** 2 - 1.0 for z in char_rho]
    irreps = {
        "1": [1 + 0j] * 24,
        "chi": chi,
        "chi2": chi2,
        "rho": char_rho,
        "rhochi": [a * b for a, b in zip(char_rho, chi)],
        "rhochi2": [a * b for a, b in zip(char_rho, chi2)],
        "3": char_3,
    }
    names = list(irreps)

    # Complete seven-irrep character system.
    for a in names:
        for b in names:
            target = 1 if a == b else 0
            assert abs(cinner(irreps[a], irreps[b]) - target) < 2e-7
    dims = {name: round(irreps[name][0].real) for name in names}
    assert dims == {
        "1": 1, "chi": 1, "chi2": 1,
        "rho": 2, "rhochi": 2, "rhochi2": 2, "3": 3,
    }
    assert sum(d * d for d in dims.values()) == 24

    # Exterior powers Lambda^k R.
    ext_chars = {k: [] for k in range(5)}
    for _, r, _, _ in records:
        es = elementary_sym4_from_traces(r)
        for k in range(5):
            ext_chars[k].append(es[k])

    expected = {
        0: {"1": 1},
        1: {"rho": 1, "rhochi": 1},
        2: {"1": 1, "chi": 1, "chi2": 1, "3": 1},
        3: {"rhochi": 1, "rhochi2": 1},
        4: {"chi2": 1},
    }
    actual = {}
    for k in range(5):
        decomp = {}
        for name in names:
            m = round_mult(cinner(irreps[name], ext_chars[k]))
            if m:
                decomp[name] = m
        actual[k] = decomp
        assert decomp == expected[k], (k, decomp)

    # Center parity: + on tensorial irreps, - on spinorial irreps.
    zkey = matrix_key(mscale(-1, I2))
    zi = [matrix_key(g) for g, _, _, _ in records].index(zkey)
    assert all(abs(irreps[n][zi] - dims[n]) < 2e-7 for n in ("1", "chi", "chi2", "3"))
    assert all(abs(irreps[n][zi] + dims[n]) < 2e-7 for n in ("rho", "rhochi", "rhochi2"))
    for k in range(5):
        assert abs(ext_chars[k][zi] - ((-1) ** k) * math.comb(4, k)) < 2e-7

    # McKay adjacency A_ij = <chi_j, rho chi_i>.
    adjacency = [[0 for _ in names] for _ in names]
    for i, ni in enumerate(names):
        tensor_char = [a * b for a, b in zip(char_rho, irreps[ni])]
        for j, nj in enumerate(names):
            adjacency[i][j] = round_mult(cinner(irreps[nj], tensor_char))

    assert adjacency == [
        [0,0,0,1,0,0,0],
        [0,0,0,0,1,0,0],
        [0,0,0,0,0,1,0],
        [1,0,0,0,0,0,1],
        [0,1,0,0,0,0,1],
        [0,0,1,0,0,0,1],
        [0,0,0,1,1,1,0],
    ]

    # Affine-E6 graph certificate: connected tree, degree sequence 1,1,1,2,2,2,3,
    # and affine Cartan null vector equal to irrep dimensions.
    assert adjacency == [list(row) for row in zip(*adjacency)]
    degrees = [sum(row) for row in adjacency]
    assert sorted(degrees) == [1,1,1,2,2,2,3]
    assert sum(degrees) // 2 == 6

    dvec = [dims[n] for n in names]
    for i in range(7):
        residual = 2 * dvec[i] - sum(adjacency[i][j] * dvec[j] for j in range(7))
        assert residual == 0

    # HOUND firewall: the current Q coefficient matrix L_{a alpha}=sqrt(2) xi_{a alpha}
    # spans only Im(conj V), a 2D spinor summand of the 4D one-particle CAR carrier.
    qcoeff = [[math.sqrt(2.0) * lambdas[a][alpha] for alpha in range(2)] for a in range(4)]
    vbar = [[z.conjugate() for z in row] for row in v]
    assert_close(qcoeff, mscale(2.0, vbar))
    assert rank(qcoeff) == 2

    print("TIR_NAIMARK_MCKAY_E6_V0_1: PASS")
    print("R_DECOMPOSITION = rho + rho*chi")
    print("FOCK_EXTERIOR_DECOMPOSITION =", actual)
    print("MCKAY_ENVELOPE = AFFINE_E6")
    print("CURRENT_SINGLE_Q_FULL_E6_REALIZATION = REJECTED_RANK2_SUBSECTOR_ONLY")


if __name__ == "__main__":
    main()
