#!/usr/bin/env python3
"""Finite regression controls for the Lorentz-transported E6 supertranslation theorem.

Checks:
- tetrahedral symmetry makes the four ray labels one transitive orbit;
- equal weights give the unique invariant weight vector and timelike rest momentum;
- fixed SL(2,C) fixtures transport the N=2-form CAR algebra correctly;
- boosted null-spinor sums reproduce P=m L L^dagger;
- conjugated binary-tetrahedral subgroups stabilize the transported momentum;
- generic boosts preserve the null decomposition but not the rest-frame Parseval metric.

This is an algebraic covariance audit, not a unitary Poincare-representation proof.
"""
from __future__ import annotations

import math

from validate_tir_naimark_mckay_e6_v0_1 import (
    I2,
    analysis_map,
    dagger,
    generate_2t,
    madd,
    matrix_key,
    mmul,
    mscale,
    msub,
    outcome_rep,
    spinor_from_bloch,
    tetra_vectors,
    zeros,
)
from validate_tir_sic_naimark_car_susy_v0_1 import (
    anticommutator,
    creation,
)

TOL = 5.0e-8


def det2(a):
    return a[0][0] * a[1][1] - a[0][1] * a[1][0]


def inv2(a):
    d = det2(a)
    return [
        [a[1][1] / d, -a[0][1] / d],
        [-a[1][0] / d, a[0][0] / d],
    ]


def maxabs(a):
    return max(abs(z) for row in a for z in row)


def assert_close(a, b, tol=TOL):
    err = maxabs(msub(a, b))
    assert err < tol, err


def outer(u, v):
    return [[u[i] * v[j].conjugate() for j in range(len(v))] for i in range(len(u))]


def mvec(a, v):
    return [sum(a[i][j] * v[j] for j in range(len(v))) for i in range(len(a))]


def linear_combo(coeffs, ops):
    out = zeros(len(ops[0]), len(ops[0][0]))
    for c, op in zip(coeffs, ops):
        out = madd(out, mscale(c, op))
    return out


def hermitian(a):
    return maxabs(msub(a, dagger(a))) < TOL


def unitary(a):
    return maxabs(msub(mmul(a, dagger(a)), I2)) < TOL


def main():
    ns = tetra_vectors()
    lambdas = [spinor_from_bloch(n) for n in ns]
    V = analysis_map(lambdas)

    group, _ = generate_2t()

    # Projective tetrahedral action: 12 permutations, transitive on four rays.
    perms = set()
    for g in group:
        _, pi, _ = outcome_rep(g, lambdas)
        perms.add(tuple(pi))
    assert len(perms) == 12
    assert {pi[0] for pi in perms} == {0, 1, 2, 3}

    # Any weight vector fixed by all transitive permutations must have equal entries.
    # Check the basis constraints generated by the actual permutation group.
    edges = set()
    for pi in perms:
        for a in range(4):
            edges.add((a, pi[a]))
    reached = {0}
    changed = True
    while changed:
        changed = False
        for a, b in edges:
            if a in reached and b not in reached:
                reached.add(b)
                changed = True
            if b in reached and a not in reached:
                reached.add(a)
                changed = True
    assert reached == {0, 1, 2, 3}

    p = 0.75
    m = 4.0 * p

    # Equal-weight rest momentum from null rays.
    spatial = [sum(p * n[j] for n in ns) for j in range(3)]
    assert max(abs(x) for x in spatial) < TOL
    assert abs(m * m - 16.0 * p * p) < TOL
    P0 = mscale(m, I2)

    # Rest Parseval/SIC frame operator.
    assert_close(mmul(dagger(V), V), I2)

    # Four complex fermionic modes labelled by (I, alpha).
    creators = [creation(a) for a in range(4)]
    annihilators = [dagger(c) for c in creators]
    i16 = [[1.0 + 0j if i == j else 0j for j in range(16)] for i in range(16)]

    # Q^I_alpha(rest) = sqrt(2m) c^dagger_{I,alpha}.
    q_rest = [[None, None], [None, None]]
    scale = math.sqrt(2.0 * m)
    for I in range(2):
        for alpha in range(2):
            q_rest[I][alpha] = mscale(scale, creators[2 * I + alpha])

    # Fixed SL(2,C) fixtures: nonunitary boosts/shears plus a unitary rotation.
    eta = 0.7
    L_boost = [
        [math.exp(eta / 2.0) + 0j, 0j],
        [0j, math.exp(-eta / 2.0) + 0j],
    ]
    L_shear = [
        [1.0 + 0j, 0.35 + 0.2j],
        [0j, 1.0 + 0j],
    ]
    theta = 0.41
    L_rot = [
        [math.cos(theta / 2.0) + 0j, -1j * math.sin(theta / 2.0)],
        [-1j * math.sin(theta / 2.0), math.cos(theta / 2.0) + 0j],
    ]
    fixtures = [L_boost, L_shear, L_rot]

    for L in fixtures:
        assert abs(det2(L) - 1.0) < TOL

        P = mmul(mmul(L, P0), dagger(L))
        assert hermitian(P)
        assert abs(det2(P) - m * m) < 2e-7
        assert (P[0][0].real > 0.0 and P[1][1].real > 0.0)

        # Boosted supercharges close on the transported momentum.
        qL = [[None, None], [None, None]]
        for I in range(2):
            for alpha in range(2):
                qL[I][alpha] = linear_combo(L[alpha], q_rest[I])

        for I in range(2):
            for J in range(2):
                for alpha in range(2):
                    for beta in range(2):
                        lhs = anticommutator(qL[I][alpha], dagger(qL[J][beta]))
                        scalar = 2.0 * P[alpha][beta] if I == J else 0j
                        rhs = mscale(scalar, i16)
                        assert_close(lhs, rhs, 2e-7)
                        assert_close(
                            anticommutator(qL[I][alpha], qL[J][beta]),
                            zeros(16, 16),
                            2e-7,
                        )

        # Boost each null spinor; equal-weight sum reproduces P.
        Psum = zeros(2, 2)
        for lam in lambdas:
            blam = mvec(L, lam)
            Psum = madd(Psum, mscale(p, mscale(2.0, outer(blam, blam))))
        assert_close(Psum, P, 2e-7)

        # Conjugated binary-tetrahedral subgroup stabilizes transported P.
        Linv = inv2(L)
        for u in group:
            g = mmul(mmul(L, u), Linv)
            assert_close(mmul(mmul(g, P), dagger(g)), P, 3e-7)

        # Rest-frame Parseval normalization transports to L L^dagger.
        boosted_frame = mmul(mmul(L, I2), dagger(L))
        direct_frame = zeros(2, 2)
        for lam in lambdas:
            phi = [z / math.sqrt(2.0) for z in lam]
            bphi = mvec(L, phi)
            direct_frame = madd(direct_frame, outer(bphi, bphi))
        assert_close(direct_frame, boosted_frame, 2e-7)

        if not unitary(L):
            assert maxabs(msub(direct_frame, I2)) > 1e-3
        else:
            assert_close(direct_frame, I2)

    print("TIR_LORENTZ_TRANSPORTED_E6_SUPERTRANSLATION_V0_1: PASS")
    print("ALGEBRAIC_SL2C_TIMELIKE_ORBIT = CLOSED")
    print("CONJUGATED_2T_LITTLE_GROUP = PASS")
    print("SIC_PARSEVAL_NORMALIZATION = REST_INTERNAL_NOT_GENERIC_BOOST_INVARIANT")
    print("FINITE_DIMENSIONAL_UNITARY_SL2C = STANDARD_NO_GO_NOT_COMPUTATION")


if __name__ == "__main__":
    main()
